### ISSUE TITLE
Crash when using Totem of Defusing

### ISSUE THREAD

**Issue by bobfrapples49** [Lemonszz/Totem-Expansion#10]
When using a totem of defusing, a creeper exploded, and the server crashed. I have attempted to log back in several times, and every time I do, the server shuts down. 
Initial Error Report: https://pastebin.com/pFXtvWrj
Subsequent Error Report: https://pastebin.com/Ha2tP9dN
Thanks.

**Comment by Lemonszz** [comment]
Update your forge
