### ISSUE TITLE
Totem drop rate confic not working?

### ISSUE THREAD

**Issue by bastie2606** [Lemonszz/Totem-Expansion#11]
Hey so i just wanted to increase the drop rate of the totem heads. But it just changed nothing i tried to but it on 1 to see if you have to lower the number.....nothing i tried to but it on 10000000 to see if you have to but it higher ......nothing so did I do something wrong or is it just bugged?

**Comment by Lemonszz** [comment]
Thanks for the report.

I just found a bit of a flaw in the logic that drops the heads. Some factors may cause the heads to never drop. 

Currently, putting the drop rate to "2" without using looting should drop a head 50% of the time.

I'll fix this up for the next release!

**Comment by bastie2606** [comment]
Thank you for the fast answer so if I understand this currently you can either have no drop or a 50% drop change. or is it possible to have other number as well?

**Comment by Lemonszz** [comment]
Any number greater than 2 should work for non-looting weapons, anything greater than 5, 7, 9 should work for looting 1/2/3.

**Comment by bastie2606** [comment]
OK i think i am not getting this now so what if i just want them do have a 5% drop change what number to i have to take sorry that i am bordering you so much with this now.

**Comment by Lemonszz** [comment]
5% would roughly be 20
