### ISSUE TITLE
Totem of Undying missing texture.

### ISSUE THREAD

**Issue by 63502** [Lemonszz/Totem-Expansion#3]
The picture explains everything. Mod version 1.0.2
![2018-04-07_00 27 59](https://user-images.githubusercontent.com/15267053/38451261-e23d8f8c-39fa-11e8-8a4a-9bd769358f51.png)

**Comment by Lemonszz** [comment]
That's strange, do you have a recourse pack on?

**Comment by Lemonszz** [comment]
Also could you please provide your entire log.

**Comment by 63502** [comment]
1. There is no resource pack.(the sword is from a mod)

2. Sure, here it is: [Latest Game Log](https://gist.github.com/63502/1b4677433b300d7fb3f70abafa575585)

**Comment by Lemonszz** [comment]
Thanks.
I coudn't recreate this myself, but I've uploaded a new version (1.0.3) that should hopefully solve this. Let me know if it works for you!
https://minecraft.curseforge.com/projects/totem-expansion/files/2549420 (once approved)
