### ISSUE TITLE
Crash when using explosive totem.

### ISSUE THREAD

**Issue by Akitori** [Lemonszz/Totem-Expansion#5]
Standing next to about to explode tnt gets this crash

[crash-2018-04-07_16.50.27-server.txt](https://github.com/Lemonszz/Totem-Expansion/files/1886762/crash-2018-04-07_16.50.27-server.txt)

**Comment by Lemonszz** [comment]
Thanks for the report.

I think the issue is you're on a slightly older version of forge, If update to the latest (14.23.2.2654) it shouldn't crash.

Let me know if you still have having issues after you've updated.
