### ISSUE TITLE
Totems Not Working When in Bauble Slot or Inventory

### ISSUE THREAD

**Issue by Spazmunki13** [Lemonszz/Totem-Expansion#6]
I've updated to the latest version (1.1.0) and even updated my forge to 2654 and for some reason if my totem is in the bauble slot or inventory, or even my hotbar but not selected, it doesn't activate. If I'm holding it then it activates perfectly fine.

It also doesn't render on my character when I put it in the bauble slot.

Here's a modlist if that helps: https://www.modlister.com/user/Spazmunki13/

**Comment by Lemonszz** [comment]
Thanks for the report!

I can't verify this on my end, does this happen with every single totem?
Could you also provide a full latest.log file.

**Comment by Lordician** [comment]
I can confirm the not rendering part.
Tried it with a clean modlist (only this mod, baubles (latest) and JEI).

A clean modlist makes the totems work fine if they are in your inventory or equipped as bauble (except for the spelunking one, but i guess that is intended), they do not render on the player though.
Them not working from your inventory or bauble slot is probably some mod interaction.
[latest.log](https://github.com/Lemonszz/Totem-Expansion/files/1887466/latest.log)
Here is a log of the clean setup. Nothing special.

**Comment by Spazmunki13** [comment]
So I tested each totem out and here are the results:

 - Totem of Ascending: works when falling into the void no matter where the charm is in my inventory, but it doesn't save you from a "lethal fall" which I assume means just a regular fall from a high place.
 - Totem of Smouldering: works from anywhere in my inventory.
 - Totem of Breathing: works from anywhere in my inventory.
 - Totem of Defusing: works from anywhere in my inventory.
 - Totem of Repairing: works from anywhere in my inventory.

It seems like it's only the Totem of Undying that doesn't work for me.

Here's the log:
[latest.log](https://github.com/Lemonszz/Totem-Expansion/files/1887618/latest.log)

EDIT: When I die with it in my inventory/bauble (not in my hand) there's a little lag and then I die.

**Comment by Lemonszz** [comment]
The render issue was simple, it was just drawing below the jacket layer of the skin.
Not activating seems to be a a bad mod interaction, I've done a fix to _hopefully_ fix this. 

Let me know if you're still having trouble.

https://minecraft.curseforge.com/projects/totem-expansion/files/2549972 V1.1.1

**Comment by Spazmunki13** [comment]
This fixed it! Thanks so much for putting this out so quickly. :D
