### ISSUE TITLE
[SilentCrash] When generating new world

### ISSUE THREAD

**Issue by drakray** [Lemonszz/Totem-Expansion#8]
https://pastebin.com/DxzNgF3U
Seems like a conflict when generating village, because AbyssalCraft add wood type to village material?

**Comment by Lemonszz** [comment]
Thanks for the report, this should be fixed in V1.1.2. If the issue persists you should report this to Abyssalcraft/Foamfix.

One approved, V1.1.2 can be found here https://minecraft.curseforge.com/projects/totem-expansion/files/2550303
