### ISSUE TITLE
Possible interaction with FoamFix when generating a desert village.

### ISSUE THREAD

**Issue by 63502** [Lemonszz/Totem-Expansion#9]
This issue is also posted on the Foamfix page.

> The following crash occurred when my game tried to generate a desert village. from what little I understand, This crash seems to be some form of interaction between FoamFix and Totem Expansion. It only seems to occur when a desert village with sandstone buildings generates. I have generated plenty of normal villages and spruce villages with no issues with both mods installed. 

[Crash Report](https://gist.github.com/63502/bca68b15089c731352399b2f5734efcb)

[Foamfix Issue](https://github.com/asiekierka/FoamFix/issues/139)

**Comment by Lemonszz** [comment]
Thanks for the report, but this was already fixed in V1.1.2
